spring:
  mvc:
<<<<<<< HEAD
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: Password1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
=======
    path match:
      matching-strategy: ant_path_matcher

  logging:
     level:
        root: INFO
>>>>>>> SwaggerLog2
