spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: Password123.
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  logging:
     level:
        root: INFO
  output:
    ansi:
      enabled: ALWAYS