spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/time_bank_db
    username: root
    password: hesoyam7
  jpa:
    database: mysql
    show-sql: true
    open-in-view: 'false'

    hibernate:
      ddl-auto: update

  logging:
     level:
       root: INFO
  output:
    ansi:
      enabled: ALWAYS
